In [1]:
import pandas as pd

In [2]:
energy=pd.read_excel('/Users/hlind/Downloads/energy.xlsx')

In [3]:
#transposing data
energy.T

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
Year,1984.00,1985.00,1986.00,1987.00,1988.00,1989.00,1990.00,1991.00,1992.00,1993.00,...,2001.00,2002.00,2003.00,2004.00,2005.00,2006.00,2007.00,2008.00,2009.00,2010.00
ResidentPopulation,235.83,237.92,240.13,242.29,244.50,246.82,249.62,252.98,256.51,259.92,...,285.08,287.80,290.33,293.05,295.75,298.59,301.58,304.38,307.01,309.35
GDP,3.93,4.22,4.46,4.74,5.10,5.48,5.80,5.99,6.34,6.67,...,10.29,10.64,11.14,11.87,12.64,13.40,14.06,14.37,14.12,14.66
HouseholdSize,2.69,2.67,2.66,2.64,2.62,2.63,2.63,2.62,2.66,2.67,...,2.58,2.57,2.57,2.57,2.57,2.56,2.56,2.57,2.59,2.58
MedianIncome,44.80,45.64,47.26,47.85,48.22,49.08,48.42,47.03,46.65,46.42,...,52.01,51.40,51.35,51.17,51.74,52.12,52.82,50.94,50.60,49.45
CostResidentialElectric,20.17,20.13,19.84,19.22,18.53,18.08,17.56,17.30,17.15,16.88,...,14.20,13.75,13.89,13.89,14.18,15.12,15.05,15.33,15.72,15.51
CostResidentialGas,5.72,5.52,5.17,4.73,4.49,4.41,4.31,4.15,4.07,4.15,...,5.28,4.28,5.09,5.55,6.33,6.63,6.14,6.28,5.52,5.11
CostResidentialOil,7.57,7.06,5.50,5.10,4.96,5.23,5.86,5.39,4.80,4.55,...,5.09,4.53,5.31,5.91,7.58,8.46,9.01,10.78,8.02,9.25
ResidentialEnergyConsumption,15.96,16.04,15.98,16.26,17.13,17.79,16.95,17.42,17.36,18.22,...,20.04,20.81,21.11,21.09,21.63,20.70,21.57,21.60,21.06,22.15

In [4]:
#renaming and transposing
energy1=energy.set_index('Year').T

In [5]:
energy1.head()

Year,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,...,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
ResidentPopulation,235.83,237.92,240.13,242.29,244.50,246.82,249.62,252.98,256.51,259.92,...,285.08,287.80,290.33,293.05,295.75,298.59,301.58,304.38,307.01,309.35
GDP,3.93,4.22,4.46,4.74,5.10,5.48,5.80,5.99,6.34,6.67,...,10.29,10.64,11.14,11.87,12.64,13.40,14.06,14.37,14.12,14.66
HouseholdSize,2.69,2.67,2.66,2.64,2.62,2.63,2.63,2.62,2.66,2.67,...,2.58,2.57,2.57,2.57,2.57,2.56,2.56,2.57,2.59,2.58
MedianIncome,44.80,45.64,47.26,47.85,48.22,49.08,48.42,47.03,46.65,46.42,...,52.01,51.40,51.35,51.17,51.74,52.12,52.82,50.94,50.60,49.45
CostResidentialElectric,20.17,20.13,19.84,19.22,18.53,18.08,17.56,17.30,17.15,16.88,...,14.20,13.75,13.89,13.89,14.18,15.12,15.05,15.33,15.72,15.51

In [6]:
#transposing to long
energy1.T

,ResidentPopulation,GDP,HouseholdSize,MedianIncome,CostResidentialElectric,CostResidentialGas,CostResidentialOil,ResidentialEnergyConsumption
Year,,,,,,,,
1984,235.83,3.93,2.69,44.80,20.17,5.72,7.57,15.96
1985,237.92,4.22,2.67,45.64,20.13,5.52,7.06,16.04
1986,240.13,4.46,2.66,47.26,19.84,5.17,5.50,15.98
1987,242.29,4.74,2.64,47.85,19.22,4.73,5.10,16.26
1988,244.50,5.10,2.62,48.22,18.53,4.49,4.96,17.13
1989,246.82,5.48,2.63,49.08,18.08,4.41,5.23,17.79
1990,249.62,5.80,2.63,48.42,17.56,4.31,5.86,16.95
1991,252.98,5.99,2.62,47.03,17.30,4.15,5.39,17.42
1992,256.51,6.34,2.66,46.65,17.15,4.07,4.80,17.36
1993,259.92,6.67,2.67,46.42,16.88,4.15,4.55,18.22
1994,263.13,7.09,2.65,46.94,16.57,4.20,4.30,18.11
1995,266.28,7.41,2.65,48.41,16.15,3.87,4.10,18.52
1996,269.39,7.84,2.64,49.11,15.62,3.94,4.55,19.50
1997,272.65,8.33,2.62,50.12,15.39,4.21,4.42,18.96
1998,275.85,8.79,2.61,51.94,14.85,4.05,3.77,18.95
1999,279.04,9.35,2.60,53.25,14.36,3.91,3.79,19.56
2000,282.17,9.95,2.58,53.16,14.02,4.39,5.49,20.42
2001,285.08,10.29,2.58,52.01,14.20,5.28,5.09,20.04
2002,287.80,10.64,2.57,51.40,13.75,4.28,4.53,20.81
2003,290.33,11.14,2.57,51.35,13.89,5.09,5.31,21.11
2004,293.05,11.87,2.57,51.17,13.89,5.55,5.91,21.09
2005,295.75,12.64,2.57,51.74,14.18,6.33,7.58,21.63
2006,298.59,13.40,2.56,52.12,15.12,6.63,8.46,20.70
2007,301.58,14.06,2.56,52.82,15.05,6.14,9.01,21.57
2008,304.38,14.37,2.57,50.94,15.33,6.28,10.78,21.60
2009,307.01,14.12,2.59,50.60,15.72,5.52,8.02,21.06
2010,309.35,14.66,2.58,49.45,15.51,5.11,9.25,22.15